Add Persistent Title option
M4444/TMatrix pull request #28
Opened 2021-07-10 07:20 UTC by zbot473

Prevents text from being overwritten by new rain streaks

2021-07-10 19:24 UTC, M4444 requested changes
Hi, thanks for contributing! I've added some review comments.
As for general stuff, the commit title could be something like "Added option to have a persistent title".
In the code, I would extend all the naming to Persistent **Title**, it's more clear but still not too long. You could also move all the functions and structures related to the option under the one related to the Title option so it has a better grouping.
The completion scripts and manual should also be updated (for reference see commit [77ecf23](https://github.com/M4444/TMatrix/commit/77ecf2359b47941a95248c2ccfeb2064b6f9f060) adding `--fade` option)

2021-07-17 18:12 UTC, zbot473 commented on include/Parser.h
> +			BOOL, "-p", "--persistent",
What would be the shorthand for that, or do you expect there to be none?

2021-07-19 10:30 UTC, M4444 commented on include/Parser.h
> +			BOOL, "-p", "--persistent",
We can just go with `--persistent-title`/`--no-persistent-title`. No need to add the shorter version.

2021-11-21 03:47 UTC, M4444 commented
Hi @zbot473. There was no recent activity from you so I was wondering how you would like to proceed with the PR?
Do you need help finishing the rest of the changes or would you like me to finish it instead?

2021-11-23 00:23 UTC, zbot473 commented
I've been caught up in the college application process so I can't really dedicate much time. 

Sorry for the delay though.

2021-11-23 11:10 UTC, M4444 commented
No worries. Hope everything goes well with college!

2026-03-19 15:24 UTC, emiliopedrollo commented
How about a probabilistic approach? With a low probability of overwriting the title?

2026-08-13 15:22 UTC, M4444 commented
@emiliopedrollo I added the persistent title. For further discussions please check #42

2026-08-13 15:24 UTC, M4444 commented
@zbot473 thank you for your PR and your interest in the project in general. I know you've been busy so I ended up making the change in the end.
Hope to see you again if you what to add or discuss any other improvement.

2026-08-13 15:24 UTC, closed without merging